name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [ published ]

env:
  TEST_FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
  TEST_FMP_API_URL: https://financialmodelingprep.com

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: ./.github/actions/setup-go
        with:
          cache: false # as of 2024-03-06, setup-go@v4 cache conflicts with golangci-lint-action@v3 cache https://github.com/golangci/golangci-lint-action/issues/135
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
  test:
    name: Run Go test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Go test cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
          key: go-test
          restore-keys: |
            go-test
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Run Go tests with coverage
        run: |
          go generate ./...
          go test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
